export const popularPlayers: PlayerProfile[] = [
  {
    player: {
      id: 1100,
      name: "E. Haaland",
      firstname: "Erling",
      lastname: "Braut Haaland",
      age: 25,
      birth: {
        date: "2000-07-21",
        place: "Leeds",
        country: "England",
      },
      nationality: "Norway",
      height: "194 cm",
      weight: "88 kg",
      number: 9,
      position: "Attacker",
      photo: "https://media.api-sports.io/football/players/1100.png",
    },
  },
  {
    player: {
      id: 278,
      name: "Kylian Mbappé",
      firstname: "Kylian",
      lastname: "Mbappé Lottin",
      age: 27,
      birth: {
        date: "1998-12-20",
        place: "Paris",
        country: "France",
      },
      nationality: "France",
      height: "178 cm",
      weight: "75 kg",
      number: 9,
      position: "Attacker",
      photo: "https://media.api-sports.io/football/players/278.png",
    },
  },
  {
    player: {
      id: 129718,
      name: "J. Bellingham",
      firstname: "Jude Victor William",
      lastname: "Bellingham",
      age: 22,
      birth: {
        date: "2003-06-29",
        place: "Stourbridge",
        country: "England",
      },
      nationality: "England",
      height: "186 cm",
      weight: "75 kg",
      number: 5,
      position: "Midfielder",
      photo: "https://media.api-sports.io/football/players/129718.png",
    },
  },
  {
    player: {
      id: 203224,
      name: "F. Wirtz",
      firstname: "Florian Richard",
      lastname: "Wirtz",
      age: 22,
      birth: {
        date: "2003-05-03",
        place: "Pulheim",
        country: "Germany",
      },
      nationality: "Germany",
      height: "176 cm",
      weight: "70 kg",
      number: 10,
      position: "Midfielder",
      photo: "https://media.api-sports.io/football/players/203224.png",
    },
  },
];
